import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/components/providers/ThemeProviders"
import { cn } from "@/lib/utils";

// One typeface for the whole app. Geist and Inter Tight were both being
// downloaded on every page while only Inter Tight actually rendered — the
// `body` rule in globals.css overrode the `font-sans` class on <html>.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <ThemeProviders>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
