import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/providers/ThemeProviders"


const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={` ${interTight.variable} min-h-full flex flex-col`}>
        <ThemeProviders>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
