import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/components/providers/ThemeProviders"
import { SmoothScroll } from "@/components/providers/SmoothScroll";
import { cn } from "@/lib/utils";
import { ToastProvider } from "@/components/providers/ToasterProvider";
import { AuthProvider } from "@/components/providers/AuthProvider";
// One typeface for the whole app. Geist and Inter Tight were both being
// downloaded on every page while only Inter Tight actually rendered — the
// `body` rule in globals.css overrode the `font-sans` class on <html>.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// Monospace, used only for the landing page's nav chips, eyebrows, and small
// caps labels. Inter remains the app's body face everywhere else.
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable,
        geistMono.variable
      )}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <ThemeProviders>
          <AuthProvider>
            <SmoothScroll>{children}</SmoothScroll>
          </AuthProvider>
        </ThemeProviders>

        <ToastProvider />
      </body>
    </html>
  );
}
