# Generated by Django 6.0.6 on 2026-09-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_checkressult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckRessult',
            new_name='CheckResult',
        ),
    ]
