# Generated by Django 6.0.6 on 2026-09-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_rename_checkressult_checkresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
