# Generated by Django 6.0.6 on 2026-08-13 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moniters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD')], default='GET', max_length=10)),
                ('interval', models.PositiveIntegerField(default=60, help_text='Monitoring interval in seconds.')),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Request timeout in seconds.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moniters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
